# Generated by Django 3.2.9 on 2021-12-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crudapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(max_length=4)),
                ('sname', models.CharField(max_length=20)),
                ('semail', models.CharField(max_length=20)),
            ],
        ),
    ]
